name: Ryan Lynt
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
pagination: 5
paginate_path: /blog/page:num
timezone:     America/New_York
author:
  name:       Ryan Lynt
  url:        http://rmlynt.com
